language: minimal
services:
  - docker
script:
  - docker build -t $DOCKER_USERNAME/riblet:latest .
  - if [ "$TRAVIS_BRANCH" = master ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $DOCKER_USERNAME/riblet; fi
